version: '3.8'
services:
  database: 
    container_name: ecomm-database-postgres
    image: postgres:16beta2-alpine
    environment:
      POSTGRES_DB: ecommercedatabase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ecommdb
    ports:
      - "5433:5432"
    volumes:
      - ./database/:/docker-entrypoint-initdb.d
  api:
    container_name: ecomm-api-express
    build: 
      context: ./api
      dockerfile: dockerfile
    volumes:
      - ./api:/usr/app
      - /usr/app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - database
      - elastic-search
  image-server: 
    container_name: image-container_name
    build:
      context: ./image-service
      dockerfile: dockerfile
    ports:
      - "8080:80"
  elastic-search: 
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: elasticsearch-container
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    depends_on:
      - database
volumes:
  esdata: