name: Run lambda unit tests

on:
  pull_request:
    branches:
      - test-branch
jobs:
  tests:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.0

      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test -- --testPathPattern=api/handlers/tests