name: Deploy Client to S3

on:
  pull_request:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
    - name: Set CI Environment Variable to false
      env:
        CI: false

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.16.0

    - name: Install dependencies
      run: npm install

    - name: Set CI Environment Variable to false
      env:
        CI: false
      run: npm run build
    

    - name: Deploy Client to S3
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws s3 sync . s3://luxuria-jewels-s3-bucket
